from dataclasses import dataclass#اداة حفظ البيانات
from Application.Common.Request import CommandRequest#الكلاس الاساسي لمتطلبات المشروع
from Application.Common.BaseCommandOptions import BaseCommandOptions

@dataclass(frozen=True)#كلاس تخزين البيانات 
class CopyOptions(BaseCommandOptions):
    force: bool = False       # خيار التجاوز
    interactive: bool = False # طلب التاكيد    

#  كائن يجمع المصدر والوجهة والخيارات
@dataclass(frozen=True)
class CopyRequestArgs:
    source: str               # مسار الملف اوالمجلد المراد نسخه
    destination: str          # مسار الهدف اوالوجهة
    options: CopyOptions      # الخيارات الإضافية المحددة أعلاه

# 3. الطلب الرئيسي الذي سيتم تمريره إلى Dispatcher
class CopyRequest(CommandRequest[CopyRequestArgs]):
    """طلب النسخ الذي يحمل المسارات والخيارات بشكل منظّم."""
    pass